import Difficulty from './Difficulty';
import Genre from './Genre';

const songList = [
    {
        id: 1,
        title: "mint tears",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 1,
        order_oni: 0
    },
    {
        id: 2,
        title: "ガンスリンガーシンデレラ",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 2,
        order_oni: 0
    },
    {
        id: 3,
        title: "ANiMA",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 3,
        order_oni: 0
    },
    {
        id: 4,
        title: "竜と黒炎の姫君",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 4,
        order_oni: 0
    },
    {
        id: 5,
        title: "Dragoon",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 5,
        order_oni: 0
    },
    {
        id: 6,
        title: "秋竜 ～Shiuryu～",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 6,
        order_oni: 0
    },
    {
        id: 7,
        title: "KAGEKIYO",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 10,
        genre: Genre.GameMusic,
        order_hard: 7,
        order_oni: 0
    },
    {
        id: 8,
        title: "紅",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 8,
        order_oni: 0
    },
    {
        id: 9,
        title: "コネクトカラーズ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 9,
        order_oni: 0
    },
    {
        id: 10,
        title: "夏竜 ～Karyu～",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 10,
        order_oni: 0
    },
    {
        id: 11,
        title: "メカデス。",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 11,
        order_oni: 0
    },
    {
        id: 12,
        title: "Shiny Kung-fu Revival",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 12,
        order_oni: 0
    },
    {
        id: 13,
        title: "The Carnivorous Carnival",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 13,
        order_oni: 0
    },
    {
        id: 14,
        title: "ルカルカ★ナイトフィーバー",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 9,
        genre: Genre.Vocaloid,
        order_hard: 14,
        order_oni: 0
    },
    {
        id: 15,
        title: "ゴーゴー・キッチン",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 15,
        order_oni: 0
    },
    {
        id: 16,
        title: "M.S.S.Planet",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.Vocaloid,
        order_hard: 16,
        order_oni: 0
    },
    {
        id: 17,
        title: "Dr.WILY STAGE 1",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.GameMusic,
        order_hard: 17,
        order_oni: 0
    },
    {
        id: 18,
        title: "フューチャー・ラボ",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 18,
        order_oni: 0
    },
    {
        id: 19,
        title: "濃紅",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 19,
        order_oni: 0
    },
    {
        id: 20,
        title: "カラ鞠の花",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 20,
        order_oni: 0
    },
    {
        id: 21,
        title: "時空庁捜査2課",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 21,
        order_oni: 0
    },
    {
        id: 22,
        title: "少女の神の粒子",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 22,
        order_oni: 0
    },
    {
        id: 23,
        title: "旋風ノ舞【地】",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 23,
        order_oni: 0
    },
    {
        id: 24,
        title: "KUSANAGI",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 24,
        order_oni: 0
    },
    {
        id: 25,
        title: "クロス・ブルー",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 25,
        order_oni: 0
    },
    {
        id: 26,
        title: "Dogbite",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.Variety,
        order_hard: 26,
        order_oni: 0
    },
    {
        id: 27,
        title: "Silent Jealousy",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 10,
        genre: Genre.Pop,
        order_hard: 27,
        order_oni: 0
    },
    {
        id: 28,
        title: "鳳凰天舞無限崩れ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 28,
        order_oni: 0
    },
    {
        id: 29,
        title: "ギガンティックO.T.N",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 10,
        genre: Genre.Vocaloid,
        order_hard: 29,
        order_oni: 0
    },
    {
        id: 30,
        title: "BLAZING VORTEX",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        [Difficulty.Ura]: 10,
        genre: Genre.GameMusic,
        order_hard: 30,
        order_oni: 0
    },
    {
        id: 31,
        title: "TO MAKE THE END OF BATTLE",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        genre: Genre.Vocaloid,
        order_hard: 31,
        order_oni: 0
    },
    {
        id: 32,
        title: "がしゃどくろ",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 32,
        order_oni: 0
    },
    {
        id: 33,
        title: "青天の黎明",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 33,
        order_oni: 0
    },
    {
        id: 34,
        title: "BLUE TOPAZ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.GameMusic,
        order_hard: 34,
        order_oni: 0
    },
    {
        id: 35,
        title: "ひよっこファンタジー",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 35,
        order_oni: 0
    },
    {
        id: 36,
        title: "Caribbean Knight",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 36,
        order_oni: 0
    },
    {
        id: 37,
        title: "天泣の律",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 37,
        order_oni: 0
    },
    {
        id: 38,
        title: "ナイト・オブ・ナイツ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.Variety,
        order_hard: 38,
        order_oni: 0
    },
    {
        id: 39,
        title: "ゴーストマスク",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.Vocaloid,
        order_hard: 29,
        order_oni: 0
    },
    {
        id: 40,
        title: "極圏",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.GameMusic,
        order_hard: 40,
        order_oni: 0
    },
    {
        id: 41,
        title: "超絶技巧系少女",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 41,
        order_oni: 0
    },
    {
        id: 42,
        title: "Clotho クロートー",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 42,
        order_oni: 0
    },
    {
        id: 43,
        title: "拝啓ドッペルゲンガー",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.Vocaloid,
        order_hard: 43,
        order_oni: 0
    },
    {
        id: 44,
        title: "秘ナルメジェドノ悲ナル憂鬱",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 44,
        order_oni: 0
    },
    {
        id: 45,
        title: "パン vs ごはん！ 大決戦！",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 45,
        order_oni: 0
    },
    {
        id: 46,
        title: "行かないでイカロス",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 46,
        order_oni: 0
    },
    {
        id: 47,
        title: "聖徳たいこの「日いずるまで飛鳥」",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 47,
        order_oni: 0
    },
    {
        id: 48,
        title: "よくでる2000",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 48,
        order_oni: 0
    },
    {
        id: 49,
        title: "Gloria",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 49,
        order_oni: 0
    },
    {
        id: 50,
        title: "Scars of FAUNA",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.GameMusic,
        order_hard: 50,
        order_oni: 0
    },
    {
        id: 51,
        title: "FREEDOM DiVE↓",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.Variety,
        order_hard: 51,
        order_oni: 0
    },
    {
        id: 52,
        title: "いっそこのままで",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 52,
        order_oni: 0
    },
    {
        id: 53,
        title: "Leviathan",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.GameMusic,
        order_hard: 53,
        order_oni: 0
    },
    {
        id: 54,
        title: "零の狂詩曲",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 54,
        order_oni: 0
    },
    {
        id: 55,
        title: "3piece-JazzParty!",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 55,
        order_oni: 0
    },
    {
        id: 56,
        title: "B.B.K.K.B.K.K.",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.Variety,
        order_hard: 56,
        order_oni: 0
    },
    {
        id: 57,
        title: "ペットショップ大戦",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 57,
        order_oni: 0
    },
    {
        id: 58,
        title: "大打音",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.GameMusic,
        order_hard: 58,
        order_oni: 0
    },
    {
        id: 59,
        title: "SAMURAI ROCKET",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 59,
        order_oni: 0
    },
    {
        id: 60,
        title: "よーいドン！",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 60,
        order_oni: 0
    },
    {
        id: 61,
        title: "激運！七福ハッピークルー",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 61,
        order_oni: 0
    },
    {
        id: 62,
        title: "Red Rose Evangel",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 62,
        order_oni: 0
    },
    {
        id: 63,
        title: "タイコタイム",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 63,
        order_oni: 0
    },
    {
        id: 64,
        title: "承認欲Q",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 64,
        order_oni: 0
    },
    {
        id: 65,
        title: "白鳥の湖～still a duckling～",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 10,
        genre: Genre.Classical,
        order_hard: 65,
        order_oni: 0
    },
    {
        id: 66,
        title: "六兆年と一夜物語",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 9,
        genre: Genre.Vocaloid,
        order_hard: 66,
        order_oni: 0
    },
    {
        id: 67,
        title: "KARMA(Tatsujin Mix)",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.GameMusic,
        order_hard: 45,
        order_oni: 0
    },
    {
        id: 68,
        title: "ナイトメア・サバイバー",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 68,
        order_oni: 0
    },
    {
        id: 69,
        title: "私立高天原学園高校・校歌",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 69,
        order_oni: 0
    },
    {
        id: 70,
        title: "電車で電車でOPA!OPA!OPA!",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.GameMusic,
        order_hard: 70,
        order_oni: 0
    },
    {
        id: 71,
        title: "Many wow bang!",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        [Difficulty.Ura]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 71,
        order_oni: 0
    },
    {
        id: 72,
        title: "春竜 ～Haryu～",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 72,
        order_oni: 0
    },
    {
        id: 73,
        title: "Surf Zapping",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.GameMusic,
        order_hard: 73,
        order_oni: 0
    },
    {
        id: 74,
        title: "カグツチ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 74,
        order_oni: 0
    },
    {
        id: 75,
        title: "クープランの墓",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 8,
        genre: Genre.Classical,
        order_hard: 75,
        order_oni: 0
    },
    {
        id: 76,
        title: "太鼓乱舞 皆伝(달인)",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 76,
        order_oni: 0
    },
    {
        id: 77,
        title: "太鼓乱舞 皆伝(현인)",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 77,
        order_oni: 0
    },
    {
        id: 78,
        title: "太鼓乱舞 皆伝(보통)",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 78,
        order_oni: 0
    },
    {
        id: 79,
        title: "SHOGYO MUJO",
        [Difficulty.Easy]: 2,
        [Difficulty.Normal]: 3,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.GameMusic,
        order_hard: 79,
        order_oni: 0
    },
    {
        id: 80,
        title: "ノるどん2000",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 80,
        order_oni: 0
    },
    {
        id: 81,
        title: "そつおめしき",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 81,
        order_oni: 0
    },
    {
        id: 82,
        title: "そつおめしき2ばん",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 82,
        order_oni: 0
    },
    {
        id: 83,
        title: "重金属フューギティブ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.Vocaloid,
        order_hard: 83,
        order_oni: 0
    },
    {
        id: 84,
        title: "ピコピコ マッピー",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.GameMusic,
        order_hard: 84,
        order_oni: 0
    },
    {
        id: 85,
        title: "Taiko Drum Monster",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 85,
        order_oni: 0
    },
    {
        id: 86,
        title: "夜想曲Op.9-2",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.Classical,
        order_hard: 86,
        order_oni: 0
    },
    {
        id: 87,
        title: "ヤマタイ★ナイトパーティー",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 87,
        order_oni: 0
    },
    {
        id: 88,
        title: "冬竜 ～Toryu～",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 88,
        order_oni: 0
    },
    {
        id: 89,
        title: "愛想笑い",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 89,
        order_oni: 0
    },
    {
        id: 90,
        title: "風の国の龍と騎士",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 90,
        order_oni: 0
    },
    {
        id: 91,
        title: "画竜点睛",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 91,
        order_oni: 0
    },
    {
        id: 92,
        title: "燎原ノ舞",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 92,
        order_oni: 0
    },
    {
        id: 93,
        title: "タベテモタベテモ",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 93,
        order_oni: 0
    },
    {
        id: 94,
        title: "天狗囃子",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 94,
        order_oni: 0
    },
    {
        id: 95,
        title: "地平線のエオリア",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        genre: Genre.NamcoOriginal,
        order_hard: 95,
        order_oni: 0
    },
    {
        id: 96,
        title: "和有るど経りて維持・序",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 96,
        order_oni: 0
    },
    {
        id: 97,
        title: "Day by Day!",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 97,
        order_oni: 0
    },
    {
        id: 98,
        title: "「ルスランとリュドミラ」序曲",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.Classical,
        order_hard: 98,
        order_oni: 0
    },
    {
        id: 99,
        title: "にゃーにゃーにゃー",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 99,
        order_oni: 0
    },
    {
        id: 100,
        title: "豊穣弥生",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 100,
        order_oni: 0
    },
    {
        id: 101,
        title: "マオウのショウタイム",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 101,
        order_oni: 0
    },
    {
        id: 102,
        title: "桜花爛漫",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 102,
        order_oni: 0
    },
    {
        id: 103,
        title: "夜明けまであと3秒",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.GameMusic,
        order_hard: 103,
        order_oni: 0
    },
    {
        id: 104,
        title: "ブレイクライン",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 104,
        order_oni: 0
    },
    {
        id: 105,
        title: "アスノヨゾラ哨戒班",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.Vocaloid,
        order_hard: 105,
        order_oni: 0
    },
    {
        id: 106,
        title: "星屑ストラック",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 106,
        order_oni: 0
    },
    {
        id: 107,
        title: "忘却のティルナノグ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 107,
        order_oni: 0
    },
    {
        id: 108,
        title: "リッジでリッジでGO!GO!GO! - GMT mashup -",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 108,
        order_oni: 0
    },
    {
        id: 109,
        title: "ハンロック",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.Classical,
        order_hard: 109,
        order_oni: 0
    },
    {
        id: 110,
        title: "RIDGE RACER STEPS - GMT remix -",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.GameMusic,
        order_hard: 110,
        order_oni: 0
    },
    {
        id: 111,
        title: "ロストワンの号哭",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.Vocaloid,
        order_hard: 111,
        order_oni: 0
    },
    {
        id: 112,
        title: "The Magician's Dream",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 112,
        order_oni: 0
    },
    {
        id: 113,
        title: "蒼の旋律",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 113,
        order_oni: 0
    },
    {
        id: 114,
        title: "Xa",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 114,
        order_oni: 0
    },
    {
        id: 115,
        title: "エゴエゴアタクシ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 115,
        order_oni: 0
    },
    {
        id: 116,
        title: "電子ドラムの達人",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 116,
        order_oni: 0
    },
    {
        id: 117,
        title: "conflict",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.Variety,
        order_hard: 117,
        order_oni: 0
    },
    {
        id: 118,
        title: "最終鬼畜妹フランドール・S",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 118,
        order_oni: 0
    },
    {
        id: 119,
        title: "EterNal Ring",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 119,
        order_oni: 0
    },
    {
        id: 120,
        title: "MEGALOVANIA",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.GameMusic,
        order_hard: 120,
        order_oni: 0
    },
    {
        id: 121,
        title: "Unite The Force",
        [Difficulty.Easy]: 2,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.GameMusic,
        order_hard: 121,
        order_oni: 0
    },
    {
        id: 122,
        title: "メタナイトの逆襲メドレー",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        [Difficulty.Ura]: 10,
        genre: Genre.GameMusic,
        order_hard: 122,
        order_oni: 0
    },
    {
        id: 123,
        title: "SAKURA EXHAUST",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 123,
        order_oni: 0
    },
    {
        id: 124,
        title: "戦え！ T3防衛隊 ～GDI mix～",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.GameMusic,
        order_hard: 124,
        order_oni: 0
    },
    {
        id: 125,
        title: "タイコロール",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 125,
        order_oni: 0
    },
    {
        id: 126,
        title: "G意識過剰",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 126,
        order_oni: 0
    },
    {
        id: 127,
        title: "ユースフルコースター",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 127,
        order_oni: 0
    },
    {
        id: 128,
        title: "ぷるぷるしんぷる",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 128,
        order_oni: 0
    },
    {
        id: 129,
        title: "Calamity Fortune",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        [Difficulty.Ura]: 10,
        genre: Genre.Variety,
        order_hard: 129,
        order_oni: 0
    },
    {
        id: 130,
        title: "セイクリッド ルイン",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 130,
        order_oni: 0
    },
    {
        id: 131,
        title: "ピコピコ ルイン",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 131,
        order_oni: 0
    },
    {
        id: 132,
        title: "てんびん座急行 夜を行く",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 132,
        order_oni: 0
    },
    {
        id: 133,
        title: "イオシス秋の肉食祭2014",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 133,
        order_oni: 0
    },
    {
        id: 134,
        title: "Heat Haze Shadow 2",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.GameMusic,
        order_hard: 134,
        order_oni: 0
    },
    {
        id: 135,
        title: "さちさちにしてあげる♪",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        [Difficulty.Ura]: 10,
        genre: Genre.Pop,
        order_hard: 135,
        order_oni: 0
    },
    {
        id: 136,
        title: "さよならワーリャ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 136,
        order_oni: 0
    },
    {
        id: 137,
        title: "カラフルボイス",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 88,
        order_oni: 0
    },
    {
        id: 138,
        title: "New World",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.GameMusic,
        order_hard: 138,
        order_oni: 0
    },
    {
        id: 139,
        title: "ナックルヘッズ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.GameMusic,
        order_hard: 139,
        order_oni: 0
    },
    {
        id: 140,
        title: "SORA-II グリーゼ581",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 3,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        genre: Genre.NamcoOriginal,
        order_hard: 140,
        order_oni: 0
    },
    {
        id: 141,
        title: "Lighting Dance",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 141,
        order_oni: 0
    },
    {
        id: 142,
        title: "つながれ！ひろがれ！打ち上がれ！",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 142,
        order_oni: 0
    },
    {
        id: 143,
        title: "熊蜂の飛行",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.Classical,
        order_hard: 143,
        order_oni: 0
    },
    {
        id: 144,
        title: "道化師の朝の歌",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.Classical,
        order_hard: 144,
        order_oni: 0
    },
    {
        id: 145,
        title: "Help me, ERINNNNNN!!",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.Variety,
        order_hard: 145,
        order_oni: 0
    },
    {
        id: 146,
        title: "ツンデレCafeへようこそ☆",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 146,
        order_oni: 0
    },
    {
        id: 147,
        title: "アサガオ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 147,
        order_oni: 0
    },
    {
        id: 148,
        title: "ドドンガド～ン",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 148,
        order_oni: 0
    },
    {
        id: 149,
        title: "God Ray",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 149,
        order_oni: 0
    },
    {
        id: 150,
        title: "SORA-VII シグナスウォール",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 150,
        order_oni: 0
    },
    {
        id: 151,
        title: "No Gravity",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 151,
        order_oni: 0
    },
    {
        id: 152,
        title: "アルムジカac14.0V",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 152,
        order_oni: 0
    },
    {
        id: 153,
        title: "No Way Back",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 153,
        order_oni: 0
    },
    {
        id: 154,
        title: "SORA-I アースライズ",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 154,
        order_oni: 0
    },
    {
        id: 155,
        title: "NECOLOGY",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 155,
        order_oni: 0
    },
    {
        id: 156,
        title: "月下美人",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 156,
        order_oni: 0
    },
    {
        id: 157,
        title: "夢色コースター",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 157,
        order_oni: 0
    },
    {
        id: 158,
        title: "What's in the box?",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 158,
        order_oni: 0
    },
    {
        id: 159,
        title: "エンジェル ドリーム",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 159,
        order_oni: 0
    },
    {
        id: 160,
        title: "エンジェル ドリーム",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.GameMusic,
        order_hard: 160,
        order_oni: 0
    },
    {
        id: 161,
        title: "Venomous",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 10,
        genre: Genre.GameMusic,
        order_hard: 161,
        order_oni: 0
    },
    {
        id: 162,
        title: "テイルズ オブ ジ アビス",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.GameMusic,
        order_hard: 162,
        order_oni: 0
    },
    {
        id: 163,
        title: "うそうそ時",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 163,
        order_oni: 0
    },
    {
        id: 164,
        title: "夢と現実の境界線",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 164,
        order_oni: 0
    },
    {
        id: 165,
        title: "Choco Chiptune",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 165,
        order_oni: 0
    },
    {
        id: 166,
        title: "Honey Heartbeat ～10 Stars Mix～",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 10,
        genre: Genre.GameMusic,
        order_hard: 166,
        order_oni: 0
    },
    {
        id: 167,
        title: "あの日出会えたキセキ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 167,
        order_oni: 0
    },
    {
        id: 168,
        title: "パステル ドリーム",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 168,
        order_oni: 0
    },
    {
        id: 169,
        title: "さいたま2000",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        genre: Genre.NamcoOriginal,
        order_hard: 169,
        order_oni: 0
    },
    {
        id: 170,
        title: "Rotter Tarmination",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 170,
        order_oni: 0
    },
    {
        id: 171,
        title: "キラメキラリ",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.GameMusic,
        order_hard: 171,
        order_oni: 0
    },
    {
        id: 172,
        title: "スーパーD&D ～完全にリードしてアイマイミー～",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.Variety,
        order_hard: 172,
        order_oni: 0
    },
    {
        id: 173,
        title: "曙光～Dawn～",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        [Difficulty.Ura]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 173,
        order_oni: 0
    },
    {
        id: 174,
        title: "チルノのパーフェクトさんすう教室",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 10,
        genre: Genre.Variety,
        order_hard: 174,
        order_oni: 0
    },
    {
        id: 175,
        title: "EDY ‐エレクトリカルダンシングヨガ‐",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 159,
        order_oni: 0
    },
    {
        id: 176,
        title: "ファンタジーゾーン OPA-OPA! -GMT remix-",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        genre: Genre.GameMusic,
        order_hard: 176,
        order_oni: 0
    },
    {
        id: 177,
        title: "幻想のサテライト",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.Variety,
        order_hard: 177,
        order_oni: 0
    },
    {
        id: 178,
        title: "ロシア民謡メドレー",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        genre: Genre.Classical,
        order_hard: 178,
        order_oni: 0
    },
    {
        id: 179,
        title: "Ladystar Wandering",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.Variety,
        order_hard: 179,
        order_oni: 0
    },
    {
        id: 180,
        title: "風雲志士",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 180,
        order_oni: 0
    },
    {
        id: 181,
        title: "Comona",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.GameMusic,
        order_hard: 181,
        order_oni: 0
    },
    {
        id: 182,
        title: "月影SASURAI",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 182,
        order_oni: 0
    },
    {
        id: 183,
        title: "R.Y.U.S.E.I.",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.Pop,
        order_hard: 183,
        order_oni: 0
    },
    {
        id: 184,
        title: "もぺもぺ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        genre: Genre.Variety,
        order_hard: 184,
        order_oni: 0
    },
    {
        id: 185,
        title: "ヘ調の協奏曲 第3楽章",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.Classical,
        order_hard: 185,
        order_oni: 0
    },
    {
        id: 186,
        title: "Good-bye my earth",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.GameMusic,
        order_hard: 186,
        order_oni: 0
    },
    {
        id: 187,
        title: "PAC-MAN CHAMPIONSHIP EDITION 2",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.GameMusic,
        order_hard: 187,
        order_oni: 0
    },
    {
        id: 188,
        title: "シンフォニック ドルアーガ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 7,
        genre: Genre.GameMusic,
        order_hard: 188,
        order_oni: 0
    },
    {
        id: 189,
        title: "三瀬川乱舞",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 189,
        order_oni: 0
    },
    {
        id: 190,
        title: "友情ぽっぷ",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 4,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 6,
        genre: Genre.NamcoOriginal,
        order_hard: 190,
        order_oni: 0
    },
    {
        id: 191,
        title: "宇宙SAMURAI",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 191,
        order_oni: 0
    },
    {
        id: 192,
        title: "Dream Tide－夢の潮流－",
        [Difficulty.Easy]: 3,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 192,
        order_oni: 0
    },
    {
        id: 193,
        title: "Phantom Rider",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        [Difficulty.Ura]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 193,
        order_oni: 0
    },
    {
        id: 194,
        title: "SORA-VI 火ノ鳥",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 194,
        order_oni: 0
    },
    {
        id: 195,
        title: "TOKIMEKI♡ですとろいやー！！",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 195,
        order_oni: 0
    },
    {
        id: 196,
        title: "ミーナのおやしき",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 5,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 196,
        order_oni: 0
    },
    {
        id: 197,
        title: "めたるぽりす",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 9,
        [Difficulty.Ura]: 9,
        genre: Genre.NamcoOriginal,
        order_hard: 197,
        order_oni: 0
    },
    {
        id: 198,
        title: "モノクロボイス",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 10,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 198,
        order_oni: 0
    },
    {
        id: 199,
        title: "ゆれるプリーツ実行委員",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 6,
        [Difficulty.Hard]: 7,
        [Difficulty.Oni]: 8,
        genre: Genre.NamcoOriginal,
        order_hard: 199,
        order_oni: 0
    },
    {
        id: 200,
        title: "第六天魔王",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 1,
        order_oni: 0
    },
    {
        id: 201,
        title: "Infinite Rebellion",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 2,
        order_oni: 0
    },
    {
        id: 202,
        title: "幽玄ノ乱",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 3,
        order_oni: 0
    },
    {
        id: 203,
        title: "poxei♦DOON",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 4,
        order_oni: 0
    },
    {
        id: 204,
        title: "ドンカマ2000",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 5,
        order_oni: 0
    },
    {
        id: 205,
        title: "まださいたま2000",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 6,
        order_oni: 0
    },
    {
        id: 206,
        title: "!!!カオスタイム!!!",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 7,
        order_oni: 0
    },
    {
        id: 207,
        title: "わら得る2000",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 8,
        order_oni: 0
    },
    {
        id: 208,
        title: "幕末維新譚",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 9,
        order_oni: 0
    },
    {
        id: 209,
        title: "森羅万象",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 10,
        order_oni: 0
    },
    {
        id: 210,
        title: "DEBSTEP!",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 11,
        order_oni: 0
    },
    {
        id: 211,
        title: "うちゅうひこうし冒険譚",
        [Difficulty.Easy]: 4,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 12,
        order_oni: 0
    },
    {
        id: 212,
        title: "続・〆ドレー2000",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 13,
        order_oni: 0
    },
    {
        id: 213,
        title: "デッド・オア・ダイ",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 14,
        order_oni: 0
    },
    {
        id: 214,
        title: "疾風怒濤",
        [Difficulty.Easy]: 5,
        [Difficulty.Normal]: 7,
        [Difficulty.Hard]: 8,
        [Difficulty.Oni]: 10,
        [Difficulty.Ura]: 10,
        genre: Genre.NamcoOriginal,
        order_hard: 15,
        order_oni: 0
    },
];

export default songList;
